language: python
python:
    - 3.6
    - 3.7
    - 3.8

before_install:
    - python --version
    - pip install -U pip pytest codecov pytest-cov

script:
    - pytest --cov-report term --cov=app/test/

after_success:
    - codecov
